"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.duration_pb2
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Chat(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _AccountStatus:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _AccountStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Chat._AccountStatus.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        Standard: Chat._AccountStatus.ValueType  # 0
        Premium: Chat._AccountStatus.ValueType  # 1

    class AccountStatus(_AccountStatus, metaclass=_AccountStatusEnumTypeWrapper): ...
    Standard: Chat.AccountStatus.ValueType  # 0
    Premium: Chat.AccountStatus.ValueType  # 1

    @typing.final
    class Modifier(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        class _Pos:
            ValueType = typing.NewType("ValueType", builtins.int)
            V: typing_extensions.TypeAlias = ValueType

        class _PosEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Chat.Modifier._Pos.ValueType], builtins.type):
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
            naka: Chat.Modifier._Pos.ValueType  # 0
            shita: Chat.Modifier._Pos.ValueType  # 1
            ue: Chat.Modifier._Pos.ValueType  # 2

        class Pos(_Pos, metaclass=_PosEnumTypeWrapper): ...
        naka: Chat.Modifier.Pos.ValueType  # 0
        shita: Chat.Modifier.Pos.ValueType  # 1
        ue: Chat.Modifier.Pos.ValueType  # 2

        class _Size:
            ValueType = typing.NewType("ValueType", builtins.int)
            V: typing_extensions.TypeAlias = ValueType

        class _SizeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Chat.Modifier._Size.ValueType], builtins.type):
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
            medium: Chat.Modifier._Size.ValueType  # 0
            small: Chat.Modifier._Size.ValueType  # 1
            big: Chat.Modifier._Size.ValueType  # 2

        class Size(_Size, metaclass=_SizeEnumTypeWrapper): ...
        medium: Chat.Modifier.Size.ValueType  # 0
        small: Chat.Modifier.Size.ValueType  # 1
        big: Chat.Modifier.Size.ValueType  # 2

        class _ColorName:
            ValueType = typing.NewType("ValueType", builtins.int)
            V: typing_extensions.TypeAlias = ValueType

        class _ColorNameEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Chat.Modifier._ColorName.ValueType], builtins.type):
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
            white: Chat.Modifier._ColorName.ValueType  # 0
            red: Chat.Modifier._ColorName.ValueType  # 1
            pink: Chat.Modifier._ColorName.ValueType  # 2
            orange: Chat.Modifier._ColorName.ValueType  # 3
            yellow: Chat.Modifier._ColorName.ValueType  # 4
            green: Chat.Modifier._ColorName.ValueType  # 5
            cyan: Chat.Modifier._ColorName.ValueType  # 6
            blue: Chat.Modifier._ColorName.ValueType  # 7
            purple: Chat.Modifier._ColorName.ValueType  # 8
            black: Chat.Modifier._ColorName.ValueType  # 9
            white2: Chat.Modifier._ColorName.ValueType  # 10
            red2: Chat.Modifier._ColorName.ValueType  # 11
            pink2: Chat.Modifier._ColorName.ValueType  # 12
            orange2: Chat.Modifier._ColorName.ValueType  # 13
            yellow2: Chat.Modifier._ColorName.ValueType  # 14
            green2: Chat.Modifier._ColorName.ValueType  # 15
            cyan2: Chat.Modifier._ColorName.ValueType  # 16
            blue2: Chat.Modifier._ColorName.ValueType  # 17
            purple2: Chat.Modifier._ColorName.ValueType  # 18
            black2: Chat.Modifier._ColorName.ValueType  # 19

        class ColorName(_ColorName, metaclass=_ColorNameEnumTypeWrapper): ...
        white: Chat.Modifier.ColorName.ValueType  # 0
        red: Chat.Modifier.ColorName.ValueType  # 1
        pink: Chat.Modifier.ColorName.ValueType  # 2
        orange: Chat.Modifier.ColorName.ValueType  # 3
        yellow: Chat.Modifier.ColorName.ValueType  # 4
        green: Chat.Modifier.ColorName.ValueType  # 5
        cyan: Chat.Modifier.ColorName.ValueType  # 6
        blue: Chat.Modifier.ColorName.ValueType  # 7
        purple: Chat.Modifier.ColorName.ValueType  # 8
        black: Chat.Modifier.ColorName.ValueType  # 9
        white2: Chat.Modifier.ColorName.ValueType  # 10
        red2: Chat.Modifier.ColorName.ValueType  # 11
        pink2: Chat.Modifier.ColorName.ValueType  # 12
        orange2: Chat.Modifier.ColorName.ValueType  # 13
        yellow2: Chat.Modifier.ColorName.ValueType  # 14
        green2: Chat.Modifier.ColorName.ValueType  # 15
        cyan2: Chat.Modifier.ColorName.ValueType  # 16
        blue2: Chat.Modifier.ColorName.ValueType  # 17
        purple2: Chat.Modifier.ColorName.ValueType  # 18
        black2: Chat.Modifier.ColorName.ValueType  # 19

        class _Font:
            ValueType = typing.NewType("ValueType", builtins.int)
            V: typing_extensions.TypeAlias = ValueType

        class _FontEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Chat.Modifier._Font.ValueType], builtins.type):
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
            defont: Chat.Modifier._Font.ValueType  # 0
            mincho: Chat.Modifier._Font.ValueType  # 1
            gothic: Chat.Modifier._Font.ValueType  # 2

        class Font(_Font, metaclass=_FontEnumTypeWrapper): ...
        defont: Chat.Modifier.Font.ValueType  # 0
        mincho: Chat.Modifier.Font.ValueType  # 1
        gothic: Chat.Modifier.Font.ValueType  # 2

        class _Opacity:
            ValueType = typing.NewType("ValueType", builtins.int)
            V: typing_extensions.TypeAlias = ValueType

        class _OpacityEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Chat.Modifier._Opacity.ValueType], builtins.type):
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
            Normal: Chat.Modifier._Opacity.ValueType  # 0
            Translucent: Chat.Modifier._Opacity.ValueType  # 1

        class Opacity(_Opacity, metaclass=_OpacityEnumTypeWrapper): ...
        Normal: Chat.Modifier.Opacity.ValueType  # 0
        Translucent: Chat.Modifier.Opacity.ValueType  # 1

        @typing.final
        class FullColor(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            R_FIELD_NUMBER: builtins.int
            G_FIELD_NUMBER: builtins.int
            B_FIELD_NUMBER: builtins.int
            r: builtins.int
            g: builtins.int
            b: builtins.int
            def __init__(
                self,
                *,
                r: builtins.int = ...,
                g: builtins.int = ...,
                b: builtins.int = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing.Literal["b", b"b", "g", b"g", "r", b"r"]) -> None: ...

        POSITION_FIELD_NUMBER: builtins.int
        SIZE_FIELD_NUMBER: builtins.int
        NAMED_COLOR_FIELD_NUMBER: builtins.int
        FULL_COLOR_FIELD_NUMBER: builtins.int
        FONT_FIELD_NUMBER: builtins.int
        OPACITY_FIELD_NUMBER: builtins.int
        position: global___Chat.Modifier.Pos.ValueType
        size: global___Chat.Modifier.Size.ValueType
        named_color: global___Chat.Modifier.ColorName.ValueType
        font: global___Chat.Modifier.Font.ValueType
        opacity: global___Chat.Modifier.Opacity.ValueType
        @property
        def full_color(self) -> global___Chat.Modifier.FullColor: ...
        def __init__(
            self,
            *,
            position: global___Chat.Modifier.Pos.ValueType = ...,
            size: global___Chat.Modifier.Size.ValueType = ...,
            named_color: global___Chat.Modifier.ColorName.ValueType = ...,
            full_color: global___Chat.Modifier.FullColor | None = ...,
            font: global___Chat.Modifier.Font.ValueType = ...,
            opacity: global___Chat.Modifier.Opacity.ValueType = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["color", b"color", "full_color", b"full_color", "named_color", b"named_color"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["color", b"color", "font", b"font", "full_color", b"full_color", "named_color", b"named_color", "opacity", b"opacity", "position", b"position", "size", b"size"]) -> None: ...
        def WhichOneof(self, oneof_group: typing.Literal["color", b"color"]) -> typing.Literal["named_color", "full_color"] | None: ...

    CONTENT_FIELD_NUMBER: builtins.int
    VPOS_FIELD_NUMBER: builtins.int
    ACCOUNT_STATUS_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    RAW_USER_ID_FIELD_NUMBER: builtins.int
    HASHED_USER_ID_FIELD_NUMBER: builtins.int
    MODIFIER_FIELD_NUMBER: builtins.int
    NO_FIELD_NUMBER: builtins.int
    content: builtins.str
    vpos: builtins.int
    account_status: global___Chat.AccountStatus.ValueType
    name: builtins.str
    raw_user_id: builtins.int
    hashed_user_id: builtins.str
    no: builtins.int
    @property
    def modifier(self) -> global___Chat.Modifier: ...
    def __init__(
        self,
        *,
        content: builtins.str = ...,
        vpos: builtins.int = ...,
        account_status: global___Chat.AccountStatus.ValueType = ...,
        name: builtins.str | None = ...,
        raw_user_id: builtins.int | None = ...,
        hashed_user_id: builtins.str | None = ...,
        modifier: global___Chat.Modifier | None = ...,
        no: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_hashed_user_id", b"_hashed_user_id", "_name", b"_name", "_raw_user_id", b"_raw_user_id", "hashed_user_id", b"hashed_user_id", "modifier", b"modifier", "name", b"name", "raw_user_id", b"raw_user_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_hashed_user_id", b"_hashed_user_id", "_name", b"_name", "_raw_user_id", b"_raw_user_id", "account_status", b"account_status", "content", b"content", "hashed_user_id", b"hashed_user_id", "modifier", b"modifier", "name", b"name", "no", b"no", "raw_user_id", b"raw_user_id", "vpos", b"vpos"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_hashed_user_id", b"_hashed_user_id"]) -> typing.Literal["hashed_user_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_name", b"_name"]) -> typing.Literal["name"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_raw_user_id", b"_raw_user_id"]) -> typing.Literal["raw_user_id"] | None: ...

global___Chat = Chat

@typing.final
class OperatorComment(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTENT_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    MODIFIER_FIELD_NUMBER: builtins.int
    LINK_FIELD_NUMBER: builtins.int
    content: builtins.str
    name: builtins.str
    link: builtins.str
    @property
    def modifier(self) -> global___Chat.Modifier: ...
    def __init__(
        self,
        *,
        content: builtins.str = ...,
        name: builtins.str | None = ...,
        modifier: global___Chat.Modifier | None = ...,
        link: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_link", b"_link", "_name", b"_name", "link", b"link", "modifier", b"modifier", "name", b"name"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_link", b"_link", "_name", b"_name", "content", b"content", "link", b"link", "modifier", b"modifier", "name", b"name"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_link", b"_link"]) -> typing.Literal["link"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_name", b"_name"]) -> typing.Literal["name"] | None: ...

global___OperatorComment = OperatorComment

@typing.final
class Jump(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTENT_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    WAIT_FIELD_NUMBER: builtins.int
    content: builtins.str
    message: builtins.str
    @property
    def wait(self) -> google.protobuf.duration_pb2.Duration: ...
    def __init__(
        self,
        *,
        content: builtins.str = ...,
        message: builtins.str = ...,
        wait: google.protobuf.duration_pb2.Duration | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["wait", b"wait"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["content", b"content", "message", b"message", "wait", b"wait"]) -> None: ...

global___Jump = Jump

@typing.final
class Redirect(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URI_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    WAIT_FIELD_NUMBER: builtins.int
    uri: builtins.str
    message: builtins.str
    @property
    def wait(self) -> google.protobuf.duration_pb2.Duration: ...
    def __init__(
        self,
        *,
        uri: builtins.str = ...,
        message: builtins.str = ...,
        wait: google.protobuf.duration_pb2.Duration | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["wait", b"wait"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "uri", b"uri", "wait", b"wait"]) -> None: ...

global___Redirect = Redirect

@typing.final
class SimpleNotification(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ICHIBA_FIELD_NUMBER: builtins.int
    QUOTE_FIELD_NUMBER: builtins.int
    EMOTION_FIELD_NUMBER: builtins.int
    CRUISE_FIELD_NUMBER: builtins.int
    PROGRAM_EXTENDED_FIELD_NUMBER: builtins.int
    RANKING_IN_FIELD_NUMBER: builtins.int
    RANKING_UPDATED_FIELD_NUMBER: builtins.int
    VISITED_FIELD_NUMBER: builtins.int
    ichiba: builtins.str
    quote: builtins.str
    emotion: builtins.str
    cruise: builtins.str
    program_extended: builtins.str
    ranking_in: builtins.str
    ranking_updated: builtins.str
    visited: builtins.str
    def __init__(
        self,
        *,
        ichiba: builtins.str = ...,
        quote: builtins.str = ...,
        emotion: builtins.str = ...,
        cruise: builtins.str = ...,
        program_extended: builtins.str = ...,
        ranking_in: builtins.str = ...,
        ranking_updated: builtins.str = ...,
        visited: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["cruise", b"cruise", "emotion", b"emotion", "ichiba", b"ichiba", "message", b"message", "program_extended", b"program_extended", "quote", b"quote", "ranking_in", b"ranking_in", "ranking_updated", b"ranking_updated", "visited", b"visited"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["cruise", b"cruise", "emotion", b"emotion", "ichiba", b"ichiba", "message", b"message", "program_extended", b"program_extended", "quote", b"quote", "ranking_in", b"ranking_in", "ranking_updated", b"ranking_updated", "visited", b"visited"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["message", b"message"]) -> typing.Literal["ichiba", "quote", "emotion", "cruise", "program_extended", "ranking_in", "ranking_updated", "visited"] | None: ...

global___SimpleNotification = SimpleNotification

@typing.final
class Gift(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ITEM_ID_FIELD_NUMBER: builtins.int
    ADVERTISER_USER_ID_FIELD_NUMBER: builtins.int
    ADVERTISER_NAME_FIELD_NUMBER: builtins.int
    POINT_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    ITEM_NAME_FIELD_NUMBER: builtins.int
    CONTRIBUTION_RANK_FIELD_NUMBER: builtins.int
    item_id: builtins.str
    advertiser_user_id: builtins.int
    advertiser_name: builtins.str
    point: builtins.int
    message: builtins.str
    item_name: builtins.str
    contribution_rank: builtins.int
    def __init__(
        self,
        *,
        item_id: builtins.str = ...,
        advertiser_user_id: builtins.int | None = ...,
        advertiser_name: builtins.str = ...,
        point: builtins.int = ...,
        message: builtins.str = ...,
        item_name: builtins.str = ...,
        contribution_rank: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_advertiser_user_id", b"_advertiser_user_id", "_contribution_rank", b"_contribution_rank", "advertiser_user_id", b"advertiser_user_id", "contribution_rank", b"contribution_rank"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_advertiser_user_id", b"_advertiser_user_id", "_contribution_rank", b"_contribution_rank", "advertiser_name", b"advertiser_name", "advertiser_user_id", b"advertiser_user_id", "contribution_rank", b"contribution_rank", "item_id", b"item_id", "item_name", b"item_name", "message", b"message", "point", b"point"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_advertiser_user_id", b"_advertiser_user_id"]) -> typing.Literal["advertiser_user_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_contribution_rank", b"_contribution_rank"]) -> typing.Literal["contribution_rank"] | None: ...

global___Gift = Gift

@typing.final
class Nicoad(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class V0(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing.final
        class Latest(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            ADVERTISER_FIELD_NUMBER: builtins.int
            POINT_FIELD_NUMBER: builtins.int
            MESSAGE_FIELD_NUMBER: builtins.int
            advertiser: builtins.str
            point: builtins.int
            message: builtins.str
            def __init__(
                self,
                *,
                advertiser: builtins.str = ...,
                point: builtins.int = ...,
                message: builtins.str | None = ...,
            ) -> None: ...
            def HasField(self, field_name: typing.Literal["_message", b"_message", "message", b"message"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing.Literal["_message", b"_message", "advertiser", b"advertiser", "message", b"message", "point", b"point"]) -> None: ...
            def WhichOneof(self, oneof_group: typing.Literal["_message", b"_message"]) -> typing.Literal["message"] | None: ...

        @typing.final
        class Ranking(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            ADVERTISER_FIELD_NUMBER: builtins.int
            RANK_FIELD_NUMBER: builtins.int
            MESSAGE_FIELD_NUMBER: builtins.int
            USER_RANK_FIELD_NUMBER: builtins.int
            advertiser: builtins.str
            rank: builtins.int
            message: builtins.str
            user_rank: builtins.int
            def __init__(
                self,
                *,
                advertiser: builtins.str = ...,
                rank: builtins.int = ...,
                message: builtins.str | None = ...,
                user_rank: builtins.int | None = ...,
            ) -> None: ...
            def HasField(self, field_name: typing.Literal["_message", b"_message", "_user_rank", b"_user_rank", "message", b"message", "user_rank", b"user_rank"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing.Literal["_message", b"_message", "_user_rank", b"_user_rank", "advertiser", b"advertiser", "message", b"message", "rank", b"rank", "user_rank", b"user_rank"]) -> None: ...
            @typing.overload
            def WhichOneof(self, oneof_group: typing.Literal["_message", b"_message"]) -> typing.Literal["message"] | None: ...
            @typing.overload
            def WhichOneof(self, oneof_group: typing.Literal["_user_rank", b"_user_rank"]) -> typing.Literal["user_rank"] | None: ...

        LATEST_FIELD_NUMBER: builtins.int
        RANKING_FIELD_NUMBER: builtins.int
        TOTAL_POINT_FIELD_NUMBER: builtins.int
        total_point: builtins.int
        @property
        def latest(self) -> global___Nicoad.V0.Latest: ...
        @property
        def ranking(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Nicoad.V0.Ranking]: ...
        def __init__(
            self,
            *,
            latest: global___Nicoad.V0.Latest | None = ...,
            ranking: collections.abc.Iterable[global___Nicoad.V0.Ranking] | None = ...,
            total_point: builtins.int = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["latest", b"latest"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["latest", b"latest", "ranking", b"ranking", "total_point", b"total_point"]) -> None: ...

    @typing.final
    class V1(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        TOTAL_AD_POINT_FIELD_NUMBER: builtins.int
        MESSAGE_FIELD_NUMBER: builtins.int
        total_ad_point: builtins.int
        message: builtins.str
        def __init__(
            self,
            *,
            total_ad_point: builtins.int = ...,
            message: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["message", b"message", "total_ad_point", b"total_ad_point"]) -> None: ...

    V0_FIELD_NUMBER: builtins.int
    V1_FIELD_NUMBER: builtins.int
    @property
    def v0(self) -> global___Nicoad.V0: ...
    @property
    def v1(self) -> global___Nicoad.V1: ...
    def __init__(
        self,
        *,
        v0: global___Nicoad.V0 | None = ...,
        v1: global___Nicoad.V1 | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["v0", b"v0", "v1", b"v1", "versions", b"versions"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["v0", b"v0", "v1", b"v1", "versions", b"versions"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["versions", b"versions"]) -> typing.Literal["v0", "v1"] | None: ...

global___Nicoad = Nicoad

@typing.final
class CommentLock(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Status:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _StatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[CommentLock._Status.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        Unrestricted: CommentLock._Status.ValueType  # 0
        Locked: CommentLock._Status.ValueType  # 1

    class Status(_Status, metaclass=_StatusEnumTypeWrapper): ...
    Unrestricted: CommentLock.Status.ValueType  # 0
    Locked: CommentLock.Status.ValueType  # 1

    STATUS_FIELD_NUMBER: builtins.int
    status: global___CommentLock.Status.ValueType
    def __init__(
        self,
        *,
        status: global___CommentLock.Status.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["status", b"status"]) -> None: ...

global___CommentLock = CommentLock

@typing.final
class CommentMode(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Layout:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _LayoutEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[CommentMode._Layout.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        Normal: CommentMode._Layout.ValueType  # 0
        SplitTop: CommentMode._Layout.ValueType  # 1
        Background: CommentMode._Layout.ValueType  # 2

    class Layout(_Layout, metaclass=_LayoutEnumTypeWrapper): ...
    Normal: CommentMode.Layout.ValueType  # 0
    SplitTop: CommentMode.Layout.ValueType  # 1
    Background: CommentMode.Layout.ValueType  # 2

    LAYOUT_FIELD_NUMBER: builtins.int
    layout: global___CommentMode.Layout.ValueType
    def __init__(
        self,
        *,
        layout: global___CommentMode.Layout.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["layout", b"layout"]) -> None: ...

global___CommentMode = CommentMode

@typing.final
class GameUpdate(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___GameUpdate = GameUpdate

@typing.final
class TrialPanel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Panel:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _PanelEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[TrialPanel._Panel.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        Hidden: TrialPanel._Panel.ValueType  # 0
        Display: TrialPanel._Panel.ValueType  # 1

    class Panel(_Panel, metaclass=_PanelEnumTypeWrapper): ...
    Hidden: TrialPanel.Panel.ValueType  # 0
    Display: TrialPanel.Panel.ValueType  # 1

    class _Mode:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _ModeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[TrialPanel._Mode.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        Allowed: TrialPanel._Mode.ValueType  # 0
        Restricted: TrialPanel._Mode.ValueType  # 1
        Forbidden: TrialPanel._Mode.ValueType  # 2

    class Mode(_Mode, metaclass=_ModeEnumTypeWrapper): ...
    Allowed: TrialPanel.Mode.ValueType  # 0
    Restricted: TrialPanel.Mode.ValueType  # 1
    Forbidden: TrialPanel.Mode.ValueType  # 2

    PANEL_FIELD_NUMBER: builtins.int
    UNQUALIFIED_USER_FIELD_NUMBER: builtins.int
    panel: global___TrialPanel.Panel.ValueType
    unqualified_user: global___TrialPanel.Mode.ValueType
    def __init__(
        self,
        *,
        panel: global___TrialPanel.Panel.ValueType = ...,
        unqualified_user: global___TrialPanel.Mode.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["panel", b"panel", "unqualified_user", b"unqualified_user"]) -> None: ...

global___TrialPanel = TrialPanel

@typing.final
class ProgramStatus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _State:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _StateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ProgramStatus._State.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        Unknown: ProgramStatus._State.ValueType  # 0
        Ended: ProgramStatus._State.ValueType  # 1

    class State(_State, metaclass=_StateEnumTypeWrapper): ...
    Unknown: ProgramStatus.State.ValueType  # 0
    Ended: ProgramStatus.State.ValueType  # 1

    STATE_FIELD_NUMBER: builtins.int
    state: global___ProgramStatus.State.ValueType
    def __init__(
        self,
        *,
        state: global___ProgramStatus.State.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["state", b"state"]) -> None: ...

global___ProgramStatus = ProgramStatus

@typing.final
class TagUpdated(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class Tag(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        TEXT_FIELD_NUMBER: builtins.int
        LOCKED_FIELD_NUMBER: builtins.int
        RESERVED_FIELD_NUMBER: builtins.int
        NICOPEDIA_URI_FIELD_NUMBER: builtins.int
        text: builtins.str
        locked: builtins.bool
        reserved: builtins.bool
        nicopedia_uri: builtins.str
        def __init__(
            self,
            *,
            text: builtins.str = ...,
            locked: builtins.bool = ...,
            reserved: builtins.bool = ...,
            nicopedia_uri: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["locked", b"locked", "nicopedia_uri", b"nicopedia_uri", "reserved", b"reserved", "text", b"text"]) -> None: ...

    TAGS_FIELD_NUMBER: builtins.int
    OWNER_LOCKED_FIELD_NUMBER: builtins.int
    owner_locked: builtins.bool
    @property
    def tags(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TagUpdated.Tag]: ...
    def __init__(
        self,
        *,
        tags: collections.abc.Iterable[global___TagUpdated.Tag] | None = ...,
        owner_locked: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["owner_locked", b"owner_locked", "tags", b"tags"]) -> None: ...

global___TagUpdated = TagUpdated

@typing.final
class Statistics(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VIEWERS_FIELD_NUMBER: builtins.int
    COMMENTS_FIELD_NUMBER: builtins.int
    AD_POINTS_FIELD_NUMBER: builtins.int
    GIFT_POINTS_FIELD_NUMBER: builtins.int
    viewers: builtins.int
    comments: builtins.int
    ad_points: builtins.int
    gift_points: builtins.int
    def __init__(
        self,
        *,
        viewers: builtins.int | None = ...,
        comments: builtins.int | None = ...,
        ad_points: builtins.int | None = ...,
        gift_points: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_ad_points", b"_ad_points", "_comments", b"_comments", "_gift_points", b"_gift_points", "_viewers", b"_viewers", "ad_points", b"ad_points", "comments", b"comments", "gift_points", b"gift_points", "viewers", b"viewers"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_ad_points", b"_ad_points", "_comments", b"_comments", "_gift_points", b"_gift_points", "_viewers", b"_viewers", "ad_points", b"ad_points", "comments", b"comments", "gift_points", b"gift_points", "viewers", b"viewers"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_ad_points", b"_ad_points"]) -> typing.Literal["ad_points"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_comments", b"_comments"]) -> typing.Literal["comments"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_gift_points", b"_gift_points"]) -> typing.Literal["gift_points"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_viewers", b"_viewers"]) -> typing.Literal["viewers"] | None: ...

global___Statistics = Statistics

@typing.final
class Marquee(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class Display(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        OPERATOR_COMMENT_FIELD_NUMBER: builtins.int
        DURATION_FIELD_NUMBER: builtins.int
        @property
        def operator_comment(self) -> global___OperatorComment: ...
        @property
        def duration(self) -> google.protobuf.duration_pb2.Duration: ...
        def __init__(
            self,
            *,
            operator_comment: global___OperatorComment | None = ...,
            duration: google.protobuf.duration_pb2.Duration | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["_duration", b"_duration", "duration", b"duration", "operator_comment", b"operator_comment"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["_duration", b"_duration", "duration", b"duration", "operator_comment", b"operator_comment"]) -> None: ...
        def WhichOneof(self, oneof_group: typing.Literal["_duration", b"_duration"]) -> typing.Literal["duration"] | None: ...

    DISPLAY_FIELD_NUMBER: builtins.int
    @property
    def display(self) -> global___Marquee.Display: ...
    def __init__(
        self,
        *,
        display: global___Marquee.Display | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_display", b"_display", "display", b"display"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_display", b"_display", "display", b"display"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_display", b"_display"]) -> typing.Literal["display"] | None: ...

global___Marquee = Marquee

@typing.final
class Enquete(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Status:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _StatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Enquete._Status.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        Closed: Enquete._Status.ValueType  # 0
        Poll: Enquete._Status.ValueType  # 1
        Result: Enquete._Status.ValueType  # 2

    class Status(_Status, metaclass=_StatusEnumTypeWrapper): ...
    Closed: Enquete.Status.ValueType  # 0
    Poll: Enquete.Status.ValueType  # 1
    Result: Enquete.Status.ValueType  # 2

    @typing.final
    class Choice(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        DESCRIPTION_FIELD_NUMBER: builtins.int
        PER_MILLE_FIELD_NUMBER: builtins.int
        description: builtins.str
        per_mille: builtins.int
        def __init__(
            self,
            *,
            description: builtins.str = ...,
            per_mille: builtins.int | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["_per_mille", b"_per_mille", "per_mille", b"per_mille"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["_per_mille", b"_per_mille", "description", b"description", "per_mille", b"per_mille"]) -> None: ...
        def WhichOneof(self, oneof_group: typing.Literal["_per_mille", b"_per_mille"]) -> typing.Literal["per_mille"] | None: ...

    QUESTION_FIELD_NUMBER: builtins.int
    CHOICES_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    question: builtins.str
    status: global___Enquete.Status.ValueType
    @property
    def choices(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Enquete.Choice]: ...
    def __init__(
        self,
        *,
        question: builtins.str = ...,
        choices: collections.abc.Iterable[global___Enquete.Choice] | None = ...,
        status: global___Enquete.Status.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["choices", b"choices", "question", b"question", "status", b"status"]) -> None: ...

global___Enquete = Enquete

@typing.final
class MoveOrder(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    JUMP_FIELD_NUMBER: builtins.int
    REDIRECT_FIELD_NUMBER: builtins.int
    @property
    def jump(self) -> global___Jump: ...
    @property
    def redirect(self) -> global___Redirect: ...
    def __init__(
        self,
        *,
        jump: global___Jump | None = ...,
        redirect: global___Redirect | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["jump", b"jump", "redirect", b"redirect", "to", b"to"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["jump", b"jump", "redirect", b"redirect", "to", b"to"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["to", b"to"]) -> typing.Literal["jump", "redirect"] | None: ...

global___MoveOrder = MoveOrder
