# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dwango/nicolive/chat/data/origin.proto
# Protobuf Python Version: 5.27.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    0,
    '',
    'dwango/nicolive/chat/data/origin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&dwango/nicolive/chat/data/origin.proto\x12\x19\x64wango.nicolive.chat.data\"s\n\x0eNicoliveOrigin\x12>\n\x04\x63hat\x18\x01 \x01(\x0b\x32..dwango.nicolive.chat.data.NicoliveOrigin.ChatH\x00\x1a\x17\n\x04\x43hat\x12\x0f\n\x07live_id\x18\x01 \x01(\x03\x42\x08\n\x06originb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dwango.nicolive.chat.data.origin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NICOLIVEORIGIN']._serialized_start=69
  _globals['_NICOLIVEORIGIN']._serialized_end=184
  _globals['_NICOLIVEORIGIN_CHAT']._serialized_start=151
  _globals['_NICOLIVEORIGIN_CHAT']._serialized_end=174
# @@protoc_insertion_point(module_scope)
