"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class NicoliveOrigin(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class Chat(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        LIVE_ID_FIELD_NUMBER: builtins.int
        live_id: builtins.int
        def __init__(
            self,
            *,
            live_id: builtins.int = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["live_id", b"live_id"]) -> None: ...

    CHAT_FIELD_NUMBER: builtins.int
    @property
    def chat(self) -> global___NicoliveOrigin.Chat: ...
    def __init__(
        self,
        *,
        chat: global___NicoliveOrigin.Chat | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["chat", b"chat", "origin", b"origin"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["chat", b"chat", "origin", b"origin"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["origin", b"origin"]) -> typing.Literal["chat"] | None: ...

global___NicoliveOrigin = NicoliveOrigin
