"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import ndgr_client.proto.dwango.nicolive.chat.data.atoms.moderator_pb2
import ndgr_client.proto.dwango.nicolive.chat.data.atoms_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class NicoliveState(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATISTICS_FIELD_NUMBER: builtins.int
    ENQUETE_FIELD_NUMBER: builtins.int
    MOVE_ORDER_FIELD_NUMBER: builtins.int
    MARQUEE_FIELD_NUMBER: builtins.int
    COMMENT_LOCK_FIELD_NUMBER: builtins.int
    COMMENT_MODE_FIELD_NUMBER: builtins.int
    TRIAL_PANEL_FIELD_NUMBER: builtins.int
    PROGRAM_STATUS_FIELD_NUMBER: builtins.int
    MODERATION_ANNOUNCEMENT_FIELD_NUMBER: builtins.int
    @property
    def statistics(self) -> ndgr_client.proto.dwango.nicolive.chat.data.atoms_pb2.Statistics: ...
    @property
    def enquete(self) -> ndgr_client.proto.dwango.nicolive.chat.data.atoms_pb2.Enquete: ...
    @property
    def move_order(self) -> ndgr_client.proto.dwango.nicolive.chat.data.atoms_pb2.MoveOrder: ...
    @property
    def marquee(self) -> ndgr_client.proto.dwango.nicolive.chat.data.atoms_pb2.Marquee: ...
    @property
    def comment_lock(self) -> ndgr_client.proto.dwango.nicolive.chat.data.atoms_pb2.CommentLock: ...
    @property
    def comment_mode(self) -> ndgr_client.proto.dwango.nicolive.chat.data.atoms_pb2.CommentMode: ...
    @property
    def trial_panel(self) -> ndgr_client.proto.dwango.nicolive.chat.data.atoms_pb2.TrialPanel: ...
    @property
    def program_status(self) -> ndgr_client.proto.dwango.nicolive.chat.data.atoms_pb2.ProgramStatus: ...
    @property
    def moderation_announcement(self) -> ndgr_client.proto.dwango.nicolive.chat.data.atoms.moderator_pb2.ModerationAnnouncement: ...
    def __init__(
        self,
        *,
        statistics: ndgr_client.proto.dwango.nicolive.chat.data.atoms_pb2.Statistics | None = ...,
        enquete: ndgr_client.proto.dwango.nicolive.chat.data.atoms_pb2.Enquete | None = ...,
        move_order: ndgr_client.proto.dwango.nicolive.chat.data.atoms_pb2.MoveOrder | None = ...,
        marquee: ndgr_client.proto.dwango.nicolive.chat.data.atoms_pb2.Marquee | None = ...,
        comment_lock: ndgr_client.proto.dwango.nicolive.chat.data.atoms_pb2.CommentLock | None = ...,
        comment_mode: ndgr_client.proto.dwango.nicolive.chat.data.atoms_pb2.CommentMode | None = ...,
        trial_panel: ndgr_client.proto.dwango.nicolive.chat.data.atoms_pb2.TrialPanel | None = ...,
        program_status: ndgr_client.proto.dwango.nicolive.chat.data.atoms_pb2.ProgramStatus | None = ...,
        moderation_announcement: ndgr_client.proto.dwango.nicolive.chat.data.atoms.moderator_pb2.ModerationAnnouncement | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_comment_lock", b"_comment_lock", "_comment_mode", b"_comment_mode", "_enquete", b"_enquete", "_marquee", b"_marquee", "_moderation_announcement", b"_moderation_announcement", "_move_order", b"_move_order", "_program_status", b"_program_status", "_statistics", b"_statistics", "_trial_panel", b"_trial_panel", "comment_lock", b"comment_lock", "comment_mode", b"comment_mode", "enquete", b"enquete", "marquee", b"marquee", "moderation_announcement", b"moderation_announcement", "move_order", b"move_order", "program_status", b"program_status", "statistics", b"statistics", "trial_panel", b"trial_panel"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_comment_lock", b"_comment_lock", "_comment_mode", b"_comment_mode", "_enquete", b"_enquete", "_marquee", b"_marquee", "_moderation_announcement", b"_moderation_announcement", "_move_order", b"_move_order", "_program_status", b"_program_status", "_statistics", b"_statistics", "_trial_panel", b"_trial_panel", "comment_lock", b"comment_lock", "comment_mode", b"comment_mode", "enquete", b"enquete", "marquee", b"marquee", "moderation_announcement", b"moderation_announcement", "move_order", b"move_order", "program_status", b"program_status", "statistics", b"statistics", "trial_panel", b"trial_panel"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_comment_lock", b"_comment_lock"]) -> typing.Literal["comment_lock"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_comment_mode", b"_comment_mode"]) -> typing.Literal["comment_mode"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_enquete", b"_enquete"]) -> typing.Literal["enquete"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_marquee", b"_marquee"]) -> typing.Literal["marquee"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_moderation_announcement", b"_moderation_announcement"]) -> typing.Literal["moderation_announcement"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_move_order", b"_move_order"]) -> typing.Literal["move_order"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_program_status", b"_program_status"]) -> typing.Literal["program_status"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_statistics", b"_statistics"]) -> typing.Literal["statistics"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_trial_panel", b"_trial_panel"]) -> typing.Literal["trial_panel"] | None: ...

global___NicoliveState = NicoliveState
