"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import ndgr_client.proto.dwango.nicolive.chat.data.message_pb2
import ndgr_client.proto.dwango.nicolive.chat.data.origin_pb2
import ndgr_client.proto.dwango.nicolive.chat.data.state_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ChunkedMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Signal:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _SignalEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ChunkedMessage._Signal.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        Flushed: ChunkedMessage._Signal.ValueType  # 0

    class Signal(_Signal, metaclass=_SignalEnumTypeWrapper): ...
    Flushed: ChunkedMessage.Signal.ValueType  # 0

    @typing.final
    class Meta(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        ID_FIELD_NUMBER: builtins.int
        AT_FIELD_NUMBER: builtins.int
        ORIGIN_FIELD_NUMBER: builtins.int
        id: builtins.str
        @property
        def at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
        @property
        def origin(self) -> ndgr_client.proto.dwango.nicolive.chat.data.origin_pb2.NicoliveOrigin: ...
        def __init__(
            self,
            *,
            id: builtins.str = ...,
            at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
            origin: ndgr_client.proto.dwango.nicolive.chat.data.origin_pb2.NicoliveOrigin | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["at", b"at", "origin", b"origin"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["at", b"at", "id", b"id", "origin", b"origin"]) -> None: ...

    META_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    SIGNAL_FIELD_NUMBER: builtins.int
    signal: global___ChunkedMessage.Signal.ValueType
    @property
    def meta(self) -> global___ChunkedMessage.Meta: ...
    @property
    def message(self) -> ndgr_client.proto.dwango.nicolive.chat.data.message_pb2.NicoliveMessage: ...
    @property
    def state(self) -> ndgr_client.proto.dwango.nicolive.chat.data.state_pb2.NicoliveState: ...
    def __init__(
        self,
        *,
        meta: global___ChunkedMessage.Meta | None = ...,
        message: ndgr_client.proto.dwango.nicolive.chat.data.message_pb2.NicoliveMessage | None = ...,
        state: ndgr_client.proto.dwango.nicolive.chat.data.state_pb2.NicoliveState | None = ...,
        signal: global___ChunkedMessage.Signal.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["message", b"message", "meta", b"meta", "payload", b"payload", "signal", b"signal", "state", b"state"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "meta", b"meta", "payload", b"payload", "signal", b"signal", "state", b"state"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["payload", b"payload"]) -> typing.Literal["message", "state", "signal"] | None: ...

global___ChunkedMessage = ChunkedMessage

@typing.final
class PackedSegment(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class Next(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        URI_FIELD_NUMBER: builtins.int
        uri: builtins.str
        def __init__(
            self,
            *,
            uri: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["uri", b"uri"]) -> None: ...

    @typing.final
    class StateSnapshot(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        URI_FIELD_NUMBER: builtins.int
        uri: builtins.str
        def __init__(
            self,
            *,
            uri: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["uri", b"uri"]) -> None: ...

    MESSAGES_FIELD_NUMBER: builtins.int
    NEXT_FIELD_NUMBER: builtins.int
    SNAPSHOT_FIELD_NUMBER: builtins.int
    @property
    def messages(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ChunkedMessage]: ...
    @property
    def next(self) -> global___PackedSegment.Next: ...
    @property
    def snapshot(self) -> global___PackedSegment.StateSnapshot: ...
    def __init__(
        self,
        *,
        messages: collections.abc.Iterable[global___ChunkedMessage] | None = ...,
        next: global___PackedSegment.Next | None = ...,
        snapshot: global___PackedSegment.StateSnapshot | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["next", b"next", "snapshot", b"snapshot"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["messages", b"messages", "next", b"next", "snapshot", b"snapshot"]) -> None: ...

global___PackedSegment = PackedSegment

@typing.final
class ChunkedEntry(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class ReadyForNext(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        AT_FIELD_NUMBER: builtins.int
        at: builtins.int
        def __init__(
            self,
            *,
            at: builtins.int = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["at", b"at"]) -> None: ...

    BACKWARD_FIELD_NUMBER: builtins.int
    PREVIOUS_FIELD_NUMBER: builtins.int
    SEGMENT_FIELD_NUMBER: builtins.int
    NEXT_FIELD_NUMBER: builtins.int
    @property
    def backward(self) -> global___BackwardSegment: ...
    @property
    def previous(self) -> global___MessageSegment: ...
    @property
    def segment(self) -> global___MessageSegment: ...
    @property
    def next(self) -> global___ChunkedEntry.ReadyForNext: ...
    def __init__(
        self,
        *,
        backward: global___BackwardSegment | None = ...,
        previous: global___MessageSegment | None = ...,
        segment: global___MessageSegment | None = ...,
        next: global___ChunkedEntry.ReadyForNext | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["backward", b"backward", "entry", b"entry", "next", b"next", "previous", b"previous", "segment", b"segment"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["backward", b"backward", "entry", b"entry", "next", b"next", "previous", b"previous", "segment", b"segment"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["entry", b"entry"]) -> typing.Literal["backward", "previous", "segment", "next"] | None: ...

global___ChunkedEntry = ChunkedEntry

@typing.final
class MessageSegment(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FROM__FIELD_NUMBER: builtins.int
    UNTIL_FIELD_NUMBER: builtins.int
    URI_FIELD_NUMBER: builtins.int
    uri: builtins.str
    @property
    def from_(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Python では from が予約されているため from_ として命名している"""

    @property
    def until(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        from_: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        until: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        uri: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["from_", b"from_", "until", b"until"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["from_", b"from_", "until", b"until", "uri", b"uri"]) -> None: ...

global___MessageSegment = MessageSegment

@typing.final
class BackwardSegment(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UNTIL_FIELD_NUMBER: builtins.int
    SEGMENT_FIELD_NUMBER: builtins.int
    SNAPSHOT_FIELD_NUMBER: builtins.int
    @property
    def until(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def segment(self) -> global___PackedSegment.Next: ...
    @property
    def snapshot(self) -> global___PackedSegment.StateSnapshot: ...
    def __init__(
        self,
        *,
        until: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        segment: global___PackedSegment.Next | None = ...,
        snapshot: global___PackedSegment.StateSnapshot | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["segment", b"segment", "snapshot", b"snapshot", "until", b"until"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["segment", b"segment", "snapshot", b"snapshot", "until", b"until"]) -> None: ...

global___BackwardSegment = BackwardSegment
